NAMES_REPLACES = {
    'Lisboa Santa Apolonia': 'Lisboa Santa Apolónia',
    'Cais do Sodre': 'Cais do Sodré',
    'Porto Campanha': 'Porto Campanhã',
    'Porto Sao Bento': 'Porto São Bento',
    'Guimaraes': 'Guimarães',
    'Leixoes': 'Leixões',
    'Leca do Balio': 'Leça do Balio',
    'Aguas Santas - Palmilheira': 'Águas Santas - Palmilheira',
    'Sao Frutuoso': 'São Frutuoso',
    'Sao Romao': 'São Romão',
    'Famalicao': 'Famalicão',
    'Midoes': 'Midões',
    'Carapecos': 'Carapeços',
    'Durraes': 'Durrães',
    'Alvaraes': 'Alvarães',
    'Valenca': 'Valença',
    'Cabeda': 'Cabêda',
    'Suzao': 'Suzão',
    'Sao Martinho do Campo': 'São Martinho do Campo',
    'Cete': 'Cête',
    'Caide': 'Caíde',
    'Vila Mea': 'Vila Meã',
    'Livracao': 'Livração',
    'Mosteiro': 'Mosteirô',
    'Mirao': 'Mirão',
    'Porto Rei': 'Porto de Rei',
    'Regua': 'Régua',
    'Ferrao': 'Ferrão',
    'Pinhao': 'Pinhão',
    'Vesuvio': 'Vesúvio',
    'Freixo de Numao - Mos do Douro': 'Freixo de Numão - Mós do Douro',
    'Carreco': 'Carreço',
    'Ancora-Praia': 'Âncora-Praia',
    'Gondarem': 'Gondarém',
    'Sao Pedro da Torre': 'São Pedro da Torre',
    'Sao Gemil': 'São Gemil',
    'Hospital Sao Joao': 'Hospital São João',
    'Sao Mamede de Infesta': 'São Mamede de Infesta',
    'Canicos': 'Caniços',
    'Ruilhe': 'Ruílhe',
    'Mazagao': 'Mazagão',
    'Braco de Prata': 'Braço de Prata',
    'Sacavem': 'Sacavém',
    'Povoa': 'Póvoa',
    'Vale de Santarem': 'Vale de Santarém',
    'Santarem': 'Santarém',
    'Riachos - Torres Novas - Golega': 'Riachos - Torres Novas - Golegã',
    'Reguengo - Vale da Pedra - Pontevel': 'Reguengo - Vale da Pedra - Pontével',
    'Chao de Macas - Fatima': 'Chão de Maçãs - Fátima',
    'Seica - Ourem': 'Seiça - Ourém',
    'Litem': 'Litém',
    'Simoes': 'Simões',
    'Vila Nova de Ancos': 'Vila Nova de Anços',
    'Formoselha - Santo Varao': 'Formoselha - Santo Varão',
    'Ademia': 'Adémia',
    'Oia': 'Oiã',
    'Valega': 'Válega',
    'Cortegaca': 'Cortegaça',
    'Coimbroes': 'Coimbrões',
    'Travasso': 'Travassô',
    'Cabanoes': 'Cabanões',
    'Casal do Alvaro': 'Casal do Álvaro',
    'Agueda': 'Águeda',
    'Carvalhal Portela': 'Carvalhal da Portela',
    'Pacos de Brandao': 'Paços de Brandão',
    'Rio Meao': 'Rio Meão',
    'Sao Joao de Ver': 'São João de Ver',
    'Escapaes': 'Escapães',
    'Sao Joao da Madeira': 'São João da Madeira',
    'Couto de Cucujaes': 'Couto de Cucujães',
    'Oliveira de Azemeis': 'Oliveira de Azeméis',
    'Vacarica': 'Vacariça',
    'Luso - Bucaco': 'Luso - Buçaco',
    'Mortagua': 'Mortágua',
    'Santa Comba Dao': 'Santa Comba Dão',
    'Papizios': 'Papízios',
    'Baracal': 'Baraçal',
    'Vila Velha de Rodao': 'Vila Velha de Ródão',
    'Benquerencas': 'Benquerenças',
    'Fundao': 'Fundão',
    'Covilha': 'Covilhã',
    'Macainhas': 'Maçainhas',
    'Ponte de Sor': 'Ponte de Sôr',
    'Chanca': 'Chança',
    'Santa Eulalia-A': 'Santa Eulália-A',
    'Monte Abraao': 'Monte Abraão',
    'Massama - Barcarena': 'Massamá - Barcarena',
    'Agualva - Cacem': 'Agualva - Cacém',
    'Merces': 'Mercês',
    'Algueirao - Mem Martins': 'Algueirão - Mem Martins',
    'Mira Sintra - Melecas': 'Mira Sintra - Meleças',
    'Obidos': 'Óbidos',
    'Sao Martinho do Porto': 'São Martinho do Porto',
    'Famalicao da Nazare': 'Famalicão da Nazaré',
    'Valado - Nazare - Alcobaca': 'Valado - Nazaré - Alcobaça',
    'Martinganca - Maceira': 'Martingança - Maceira',
    'Lourical': 'Louriçal',
    'Bifurcacao de Lares': 'Bifurcação de Lares',
    'Alcantara - Terra': 'Alcântara - Terra',
    'Setubal': 'Setúbal',
    'Alcantara - Mar': 'Alcântara - Mar',
    'Belem': 'Belém',
    'Alges': 'Algés',
    'Paco de Arcos': 'Paço de Arcos',
    'Sao Pedro do Estoril': 'São Pedro do Estoril',
    'Sao Joao do Estoril': 'São João do Estoril',
    'Poceirao': 'Poceirão',
    'Fernando Po': 'Fernando Pó',
    'Pegoes': 'Pegões',
    'Sao Joao das Craveiras': 'São João das Craveiras',
    'Bom Joao': 'Bom João',
    'Olhao': 'Olhão',
    'Conceicao': 'Conceição',
    'Vila Real de Santo Antonio': 'Vila Real de Santo António',
    'Alcacovas': 'Alcáçovas',
    'Santa Clara - Saboia': 'Santa Clara - Sabóia',
    'Loule': 'Loulé',
    'Evora': 'Évora',
    'Poco Barreto': 'Poço Barreto',
    'Estombar - Lagoa': 'Estômbar - Lagoa',
    'Portimao': 'Portimão',
    'Grandola': 'Grândola',
}

def get_fixed_name(name: str) -> str:
    name = name.replace("  ", " ")
    return NAMES_REPLACES.get(name, name).replace(" - ", "-").strip()