name: Download and Enhance CP GTFS

on:
    # schedule:
    #     - cron: "*/5 1 * * *"
    workflow_dispatch:

jobs:
    enhance:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: install deps
              run: pip install -r requirements.txt

            - name: run pipeline
              run: python enhance.py

            - name: upload gtfs
              if: success()
              uses: actions/upload-artifact@v4
              with:
                  name: cp-gtfs-enhanced
                  path: data/enhanced/*.zip
